CREATE TABLE "UserData" (
    "Id" SERIAL PRIMARY KEY,
    "Alias" VARCHAR(30) NOT NULL,
    "Email" VARCHAR(50) UNIQUE NOT NULL,
    "CreateDate" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"Address" VARCHAR(200) NOT NULL,
	"Name" VARCHAR(200) NOT NULL,
	"Password" VARCHAR(255) NOT NULL,
	"Telephone" VARCHAR(30) NOT NULL
	);